import FiniteGenomeIdentifiability
import WongDiamond
import WongSimplification
import WongIntervalNormalization
import WongBreakpointCells
import WongEventEncoding
import WongLocalArity
import WongExamples
import WongAlexander
import WongGARG
import RealBridges
import PortEncoding
import StatefulCAReal

/-! Selected endpoints for the optional real-number development. -/
#print axioms RealBridges.finiteCover_iff_setFinite
#print axioms RealBridges.BinaryRealPopulation.root_iff
#print axioms RealBridges.BinaryRealPopulation.reindexed_population
#print axioms RealBridges.eventuallyPeriodic_realized
#print axioms RealBridges.finite_real_sublevels_of_strict
#print axioms RealBridges.real_sharp_bound
#print axioms RealBridges.real_coefficient_optimal
#print axioms RealBridges.real_intersection_subset_weighted_mix
#print axioms RealBridges.convex_hull_intersection_subset_weighted_mix
#print axioms RealBridges.coefficient_from_late_witnesses
#print axioms RealBridges.finite_edit_real_bound
#print axioms RealBridges.finite_edit_real_coefficient_optimal
#print axioms RealBridges.phase_real_bound
#print axioms RealBridges.phase_maximum_exists
#print axioms RealBridges.phase_real_coefficient_optimal
#print axioms RealBridges.binary_real_classification
#print axioms RealBridges.real_subcritical_impossible
#print axioms RealBridges.real_at_least_k_distinct_roots
#print axioms RealBridges.real_alphabet_le_root_cover_length
#print axioms PortEncoding.eventual_encoding
#print axioms PortEncoding.encoding_exact
#print axioms PortEncoding.encoding_fair
#print axioms PortEncoding.encoding_legal
#print axioms PortEncoding.tail_label_lt
#print axioms PortEncoding.cut_width_constant
#print axioms PortEncoding.encoded_periodic_realizes
#print axioms StatefulCAReal.static_east_optimum
#print axioms StatefulCAReal.static_east_support_one
#print axioms StatefulCAReal.real_horizontal_spaceship_speed_zero
#print axioms StatefulCAReal.real_static_gap_and_global_obstruction

#print axioms WongGARG.GARG.locus_path_topology
#print axioms WongGARG.GARG.locus_acyclic
#print axioms WongGARG.GARG.topology_iff_erased
#print axioms WongGARG.GARG.extracted_eq_local_iff_sampleSupported
#print axioms WongGARG.GARG.local_parent_representation
#print axioms WongGARG.GARG.local_ancestors_comparable
#print axioms WongGARG.GARG.locus_path_projects
#print axioms WongGARG.GARG.exists_finite_topological_numbering
#print axioms WongGARG.GARG.ancestry_constant_without_breakpoint
#print axioms WongGARG.GARG.natTopology_path_iff

#print axioms WongAlexander.sample_ancestral_iff
#print axioms WongAlexander.extracted_sample_path_iff
#print axioms WongAlexander.finite_catalog_not_infinite
#print axioms WongAlexander.natural_biosphere_has_real_dates
#print axioms WongAlexander.ordered_encoded_prefix
#print axioms WongAlexander.old_encoded_path_iff
#print axioms WongAlexander.actual_garg_opposite_infinite_completions
#print axioms WongAlexander.extracted_contracted_sample_path_iff
#print axioms WongExamples.splitGARG
#print axioms WongExamples.tailGARG
#print axioms WongExamples.all_extracted_relations_equal
#print axioms WongExamples.raw_locus_relations_differ
#print axioms WongExamples.finite_garg_sample_reconstruction_boundary
#print axioms WongLocalArity.local_children_subset
#print axioms WongLocalArity.local_arity_le_graph_arity
#print axioms WongLocalArity.graph_unary_local_zero_or_one
#print axioms WongLocalArity.graph_unary_present_locally_unary
#print axioms WongLocalArity.backward_local_walk_bound
#print axioms WongLocalArity.no_infinite_backward_local_walk
#print axioms WongLocalArity.backward_parent_array_bound
#print axioms WongEventEncoding.ParentSpec.parent_iff_exists_at
#print axioms WongEventEncoding.EventGraph.encoded_topology
#print axioms WongEventEncoding.EventGraph.encoded_atLocus
#print axioms WongEventEncoding.EventGraph.encoded_nonempty_annotations
#print axioms WongEventEncoding.EventGraph.encoded_unique_parent
#print axioms WongEventEncoding.EventGraph.encoded_route
#print axioms WongEventEncoding.EventGraph.encoded_path_iff
#print axioms WongEventEncoding.EventGraph.erased_encoded_topology
#print axioms WongEventEncoding.EventGraph.encoded_parent_pointer
#print axioms WongEventEncoding.ParentSpec.crossover_cut_identified

#print axioms WongBreakpointCells.cells_pairwise_disjoint

#print axioms WongBreakpointCells.exists_cell_of_bracket

#print axioms WongBreakpointCells.locus_covered

#print axioms WongBreakpointCells.locus_constant_on_cell

#print axioms WongIntervalNormalization.CellPresentation.finite_cell_representation

#print axioms WongIntervalNormalization.restriction_union_acyclic

#print axioms WongIntervalNormalization.contraction_union_acyclic

#print axioms WongIntervalNormalization.sample_restriction_representable

#print axioms WongIntervalNormalization.extracted_contraction_representable

#print axioms WongIntervalNormalization.reencoded_contraction_sample_paths

#print axioms WongSimplification.automaticPresentation

#print axioms WongSimplification.automatic_sample_restriction

#print axioms WongSimplification.contraction_unique_parent

#print axioms WongSimplification.automatic_reencoded_simplification

#print axioms WongSimplification.reencoding_breakpoints_subset

#print axioms WongDiamond.garg

#print axioms WongDiamond.nonempty_annotations

#print axioms WongDiamond.canonical_records

#print axioms WongDiamond.unique_parent

#print axioms WongDiamond.sample_supported

#print axioms WongDiamond.contracted_relation_iff

#print axioms WongDiamond.retained_ancestry_iff

#print axioms WongDiamond.sample_ancestry_iff

#print axioms WongDiamond.contracted_relations_agree

#print axioms WongDiamond.raw_relations_differ

#print axioms WongDiamond.diamond_cutoff_information_loss

#print axioms WongDiamond.collapsed_represents_contraction

#print axioms WongDiamond.same_finite_output_hides_cutoff

#print axioms FiniteGenomeIdentifiability.opposite_compatible_completions

#print axioms FiniteGenomeIdentifiability.no_exact_specieslike_verdict

#print axioms FiniteGenomeIdentifiability.no_exact_specieslike_decoder
