import WongMarkedLaw
import WongMarkedMeasurable
import Mathlib.MeasureTheory.Integral.Lebesgue.Basic

set_option autoImplicit false

/-! # Conditional law of an adaptively selected spatial mark

An independent coordinate array is not enough by itself to identify the law
of a coordinate selected from a random frontier. This module proves the
countable-frontier cylinder identity and derives the required independence
from strictly earlier time rows of the actual WongMarkedLaw innovation law.

The final application derives adaptedness of the actual recorder from its
coordinate-measurability theorem and proves its spatial-mark cylinder law.
It does not assume the target probability identity or a graph projection law.
-/

namespace WongAdaptiveSelection

open MeasureTheory ProbabilityTheory Function
open scoped ENNReal NNReal BigOperators Classical

noncomputable section

section General

variable {Omega State Mark : Type*}
variable [mOmega : MeasurableSpace Omega] [MeasurableSpace State]
variable [MeasurableSingletonClass State] [Countable State]
variable [mMark : MeasurableSpace Mark]

/-- Evaluating a countable indexed family at a measurable random index is
measurable. The family need not be independent for this statement. -/
theorem measurable_selected (selector : Omega → State) (hselector : Measurable selector)
    (X : State → Omega → Mark) (hX : ∀ s, Measurable (X s)) :
    Measurable (fun omega => X (selector omega) omega) := by
  have heval : Measurable (fun p : Omega × State => X p.2 p.1) :=
    measurable_from_prod_countable_left hX
  exact heval.comp (measurable_id.prodMk hselector)

/-- Countable disjoint-fibre decomposition. The independence hypotheses concern
each fixed coordinate and its selector fibre, not the desired adaptive law. -/
theorem selector_cylinder_of_fibre_independence
    (mu : Measure Omega) (selector : Omega → State) (hselector : Measurable selector)
    (X : State → Omega → Mark) (hX : ∀ s, Measurable (X s))
    (A : Set Omega) (hA : MeasurableSet A) (B : Set Mark) (hB : MeasurableSet B)
    (hindep : ∀ s, IndepSet (A ∩ selector ⁻¹' {s}) ((X s) ⁻¹' B) mu) :
    mu (A ∩ {omega | X (selector omega) omega ∈ B}) =
      ∑' s, mu (A ∩ selector ⁻¹' {s}) * (mu.map (X s)) B := by
  let E : State → Set Omega := fun s => (A ∩ selector ⁻¹' {s}) ∩ (X s) ⁻¹' B
  have hE : ∀ s, MeasurableSet (E s) := fun s =>
    (hA.inter (hselector (measurableSet_singleton s))).inter (hX s hB)
  have hdisj : Pairwise (Disjoint on E) := by
    intro s t hst
    apply Set.disjoint_left.mpr
    intro omega hs ht
    have hes : selector omega = s := Set.mem_singleton_iff.mp hs.1.2
    have het : selector omega = t := Set.mem_singleton_iff.mp ht.1.2
    exact hst (hes.symm.trans het)
  have heq : A ∩ {omega | X (selector omega) omega ∈ B} = ⋃ s, E s := by
    ext omega
    constructor
    · intro h
      exact Set.mem_iUnion.mpr ⟨selector omega, ⟨⟨h.1, by simp⟩, h.2⟩⟩
    · intro h
      obtain ⟨s, hs⟩ := Set.mem_iUnion.mp h
      have hes : selector omega = s := Set.mem_singleton_iff.mp hs.1.2
      refine ⟨hs.1.1, ?_⟩
      change X (selector omega) omega ∈ B
      rw [hes]
      exact hs.2
  rw [heq, measure_iUnion hdisj hE]
  apply tsum_congr
  intro s
  change mu ((A ∩ selector ⁻¹' {s}) ∩ (X s) ⁻¹' B) = _
  rw [(hindep s).measure_inter_eq_mul, Measure.map_apply (hX s) hB]

/-- A fixed-coordinate independence statement with a past sigma-field implies
the full adaptive cylinder law for every measurable event in that past. -/
theorem selector_cylinder_of_past
    (mu : Measure Omega) (past : MeasurableSpace Omega) (hpast : past ≤ mOmega)
    (selector : Omega → State) (hselector : Measurable[past] selector)
    (X : State → Omega → Mark) (hX : ∀ s, Measurable[mOmega, mMark] (X s))
    (A : Set Omega) (hA : MeasurableSet[past] A)
    (B : Set Mark) (hB : MeasurableSet B)
    (hindep : ∀ s, Indep past (mMark.comap (X s)) mu) :
    mu (A ∩ {omega | X (selector omega) omega ∈ B}) =
      ∑' s, mu (A ∩ selector ⁻¹' {s}) *
        (@Measure.map Omega Mark mOmega mMark (X s) mu) B := by
  letI : MeasurableSpace Omega := mOmega
  apply selector_cylinder_of_fibre_independence mu selector
    (hselector.mono hpast le_rfl) X hX A (hpast A hA) B hB
  intro s
  apply (hindep s).indepSet_of_measurableSet
  · exact hA.inter (hselector (measurableSet_singleton s))
  · exact ⟨B, hB, rfl⟩

end General

open WongMarkedLaw

/-- Sigma-field generated by one spatial innovation coordinate. -/
def coordinateSigma (ix : InnovationIndex) : MeasurableSpace Innovations :=
  (inferInstance : MeasurableSpace SpatialMark).comap (fun M => M ix)

/-- All innovations with event index strictly smaller than t. In particular,
no alternative frontier coordinate from the current row is revealed. -/
def pastSigma (t : ℕ) : MeasurableSpace Innovations :=
  ⨆ ix : InnovationIndex, ⨆ (_ : ix.1 < t), coordinateSigma ix

theorem coordinateSigma_le (ix : InnovationIndex) :
    coordinateSigma ix ≤ (inferInstance : MeasurableSpace Innovations) :=
  (measurable_pi_apply ix).comap_le

theorem pastSigma_le (t : ℕ) :
    pastSigma t ≤ (inferInstance : MeasurableSpace Innovations) :=
  iSup_le fun ix => iSup_le fun _ => coordinateSigma_le ix

/-- Every strictly earlier coordinate is measurable in the innovation past. -/
theorem measurable_past_coordinate (t j : ℕ) (s : Finset ℕ) (hj : j < t) :
    Measurable[pastSigma t] (fun M : Innovations => M (j, s)) := by
  apply Measurable.of_comap_le
  exact le_iSup_of_le (j, s) (le_iSup_of_le hj le_rfl)

/-- This is joint independence of a present coordinate from the entire earlier
array sigma-field, stronger than pairwise coordinate independence. -/
theorem past_independent_current (L : ℝ) (hL : 0 < L) (t : ℕ) (s : Finset ℕ) :
    Indep (pastSigma t) (coordinateSigma (t, s)) (innovationLaw L hL) := by
  have hi : iIndep coordinateSigma (innovationLaw L hL) :=
    (iIndepFun_iff_iIndep (fun _ : InnovationIndex =>
      (inferInstance : MeasurableSpace SpatialMark))
      (fun ix (M : Innovations) => M ix) (innovationLaw L hL)).mp
        (innovations_independent L hL)
  let T : Set InnovationIndex := {ix | ix.1 < t}
  have hd : Disjoint T ({(t, s)} : Set InnovationIndex) := by
    apply Set.disjoint_left.mpr
    intro ix hix his
    have heq : ix = (t, s) := Set.mem_singleton_iff.mp his
    subst ix
    exact Nat.lt_irrefl t hix
  have h := indep_iSup_of_disjoint coordinateSigma_le hi hd
  simpa [pastSigma, T] using h

/-- Actual adaptive spatial-mark law under the constructed independent array.
The selector may depend on every earlier row, and the event A may use the
same past. No assumption that the selected coordinate is independent is made. -/
theorem adaptive_mark_cylinder (L : ℝ) (hL : 0 < L) (t : ℕ)
    (selector : Innovations → Finset ℕ) (hselector : Measurable[pastSigma t] selector)
    (A : Set Innovations) (hA : MeasurableSet[pastSigma t] A)
    (B : Set SpatialMark) (hB : MeasurableSet B) :
    innovationLaw L hL (A ∩ {M | M (t, selector M) ∈ B}) =
      ∑' s, innovationLaw L hL (A ∩ selector ⁻¹' {s}) * markLaw L hL s B := by
  have h := selector_cylinder_of_past (innovationLaw L hL) (pastSigma t)
    (pastSigma_le t) selector hselector (fun s (M : Innovations) => M (t, s))
    (fun s => measurable_pi_apply (t, s)) A hA B hB
    (fun s => past_independent_current L hL t s)
  simpa only [innovation_marginal] using h

theorem measurable_adaptive_mark (t : ℕ) (selector : Innovations → Finset ℕ)
    (hselector : Measurable[pastSigma t] selector) :
    Measurable (fun M : Innovations => M (t, selector M)) :=
  measurable_selected selector (hselector.mono (pastSigma_le t) le_rfl)
    (fun s (M : Innovations) => M (t, s)) (fun s => measurable_pi_apply (t, s))

/-- Fixed mark-coordinate marginal on the full count, clock, and innovation
sample space. This is only an ingredient of the adaptive result below. -/
theorem law_mark_marginal (L : ℝ) (hL : 0 < L) (θ : ℝ≥0) (n : ℕ)
    (ix : InnovationIndex) :
    (law L hL θ n).map (fun z : Sample => z.2 ix) = markLaw L hL ix.2 := by
  change (law L hL θ n).map ((fun M : Innovations => M ix) ∘ Prod.snd) = _
  rw [← Measure.map_map (measurable_pi_apply ix) measurable_snd,
    mark_array_marginal, innovation_marginal]

/-- A current spatial coordinate is independent of an event which is jointly
measurable and, after fixing the entire count-clock path, uses only earlier
innovation rows. This product-space argument uses Fubini; it does not infer
joint independence from two separate pairwise-independence claims. -/
theorem product_past_indepSet (L : ℝ) (hL : 0 < L) (θ : ℝ≥0) (n t : ℕ)
    (s : Finset ℕ) (A : Set Sample) (hA : MeasurableSet A)
    (hsections : ∀ z : WongWaitingTimes.Sample,
      MeasurableSet[pastSigma t] (Prod.mk z ⁻¹' A))
    (B : Set SpatialMark) (hB : MeasurableSet B) :
    IndepSet A ((fun z : Sample => z.2 (t, s)) ⁻¹' B) (law L hL θ n) := by
  have hY : Measurable (fun z : Sample => z.2 (t, s)) :=
    (measurable_pi_apply (t, s)).comp measurable_snd
  apply (indepSet_iff_measure_inter_eq_mul hA (hY hB) (law L hL θ n)).mpr
  rw [← Measure.map_apply hY hB, law_mark_marginal]
  change ((WongWaitingTimes.jointLaw θ n).prod (innovationLaw L hL))
      (A ∩ (fun z : Sample => z.2 (t, s)) ⁻¹' B) =
    ((WongWaitingTimes.jointLaw θ n).prod (innovationLaw L hL)) A * markLaw L hL s B
  rw [Measure.prod_apply (hA.inter (hY hB)), Measure.prod_apply hA]
  calc
    (∫⁻ z, innovationLaw L hL
        (Prod.mk z ⁻¹' (A ∩ (fun z : Sample => z.2 (t, s)) ⁻¹' B))
        ∂WongWaitingTimes.jointLaw θ n) =
      ∫⁻ z, innovationLaw L hL (Prod.mk z ⁻¹' A) * markLaw L hL s B
        ∂WongWaitingTimes.jointLaw θ n := by
      apply lintegral_congr
      intro z
      have h := (past_independent_current L hL t s).indepSet_of_measurableSet
        (hsections z) (show MeasurableSet[coordinateSigma (t, s)]
          ((fun M : Innovations => M (t, s)) ⁻¹' B) from ⟨B, hB, rfl⟩)
      have hh := h.measure_inter_eq_mul
      rw [← Measure.map_apply (measurable_pi_apply (t, s)) hB,
        innovation_marginal] at hh
      exact hh
    _ = (∫⁻ z, innovationLaw L hL (Prod.mk z ⁻¹' A)
        ∂WongWaitingTimes.jointLaw θ n) * markLaw L hL s B :=
      lintegral_mul_const _ (measurable_measure_prodMk_left hA)

/-- The adaptive mark cylinder law on the actual full sample space. The entire
count-clock path may be fixed when checking sectionwise adaptedness because it
is independent of the mark array. This larger information set is used only for
the spatial-mark law, not for a conditional exponential waiting-time claim. -/
theorem product_adaptive_mark_cylinder (L : ℝ) (hL : 0 < L) (θ : ℝ≥0) (n t : ℕ)
    (selector : Sample → Finset ℕ) (hselector : Measurable selector)
    (hsections : ∀ z : WongWaitingTimes.Sample,
      Measurable[pastSigma t] (fun M : Innovations => selector (z, M)))
    (A : Set Sample) (hA : MeasurableSet A)
    (hAsections : ∀ z : WongWaitingTimes.Sample,
      MeasurableSet[pastSigma t] (Prod.mk z ⁻¹' A))
    (B : Set SpatialMark) (hB : MeasurableSet B) :
    law L hL θ n (A ∩ {z | z.2 (t, selector z) ∈ B}) =
      ∑' s, law L hL θ n (A ∩ selector ⁻¹' {s}) * markLaw L hL s B := by
  have h := selector_cylinder_of_fibre_independence (law L hL θ n)
    selector hselector (fun s (z : Sample) => z.2 (t, s))
    (fun s => (measurable_pi_apply (t, s)).comp measurable_snd) A hA B hB
    (fun s => product_past_indepSet L hL θ n t s (A ∩ selector ⁻¹' {s})
      (hA.inter (hselector (measurableSet_singleton s)))
      (fun z => (hAsections z).inter ((hsections z) (measurableSet_singleton s))) B hB)
  simpa only [law_mark_marginal] using h

open WongMarkedRecorder WongMarkedProcess WongMarkedMeasurable

/-- The actual recorder frontier, totalized by the empty frontier only when
the prefix has failed. On every legal prefix this is its actual active set. -/
def recorderFrontier (L : ℝ) (hL : 0 < L) (n t : ℕ) (z : Sample) : Finset ℕ :=
  ((recordPrefix L hL n z t).getD defaultState).active

theorem measurable_recorderFrontier (L : ℝ) (hL : 0 < L) (n t : ℕ) :
    Measurable (recorderFrontier L hL n t) :=
  measurable_active.comp (measurable_getD.comp (measurable_recordPrefix L hL n t))

/-- The concrete recorder is adapted after fixing the count-clock path.
This is derived from its actual recursive operations and Borel encoding. -/
theorem measurable_recordPrefix_section (L : ℝ) (hL : 0 < L) (n t : ℕ)
    (z : WongWaitingTimes.Sample) :
    Measurable[pastSigma t] (fun M : Innovations => recordPrefix L hL n (z, M) t) := by
  letI : MeasurableSpace Innovations := pastSigma t
  apply measurable_recordPrefix_of_coordinates L hL n t (fun M : Innovations => (z, M))
  · intro j hj
    exact measurable_const (a := z.1 j)
  · intro j hj s
    exact measurable_past_coordinate t j s hj

theorem measurable_recorderFrontier_section (L : ℝ) (hL : 0 < L) (n t : ℕ)
    (z : WongWaitingTimes.Sample) :
    Measurable[pastSigma t] (fun M : Innovations => recorderFrontier L hL n t (z, M)) :=
  measurable_active.comp (measurable_getD.comp (measurable_recordPrefix_section L hL n t z))

/-- Exact conditional spatial-mark law of the concrete recorder, tested
against every measurable event in the full count-clock path and actual
t-event prefix. The larger count-clock information is appropriate only
for this mark-law assertion. No adaptation hypothesis about the recorder
is assumed: the previous theorem establishes it. -/
theorem recorder_mark_cylinder (L : ℝ) (hL : 0 < L) (θ : ℝ≥0) (n t : ℕ)
    (H : Set (WongWaitingTimes.Sample × Option (RawState ℝ))) (hH : MeasurableSet H)
    (B : Set SpatialMark) (hB : MeasurableSet B) :
    law L hL θ n ({z | (z.1, recordPrefix L hL n z t) ∈ H} ∩
      {z | z.2 (t, recorderFrontier L hL n t z) ∈ B}) =
      ∑' s, law L hL θ n ({z | (z.1, recordPrefix L hL n z t) ∈ H} ∩
        (recorderFrontier L hL n t) ⁻¹' {s}) * markLaw L hL s B := by
  apply product_adaptive_mark_cylinder L hL θ n t (recorderFrontier L hL n t)
    (measurable_recorderFrontier L hL n t) (measurable_recorderFrontier_section L hL n t)
    {z | (z.1, recordPrefix L hL n z t) ∈ H}
  · exact (measurable_fst.prodMk (measurable_recordPrefix L hL n t)) hH
  · intro z
    exact (measurable_const.prodMk (measurable_recordPrefix_section L hL n t z)) hH
  · exact hB

#print axioms measurable_selected
#print axioms selector_cylinder_of_fibre_independence
#print axioms selector_cylinder_of_past
#print axioms measurable_past_coordinate
#print axioms past_independent_current
#print axioms adaptive_mark_cylinder
#print axioms measurable_adaptive_mark
#print axioms law_mark_marginal
#print axioms product_past_indepSet
#print axioms product_adaptive_mark_cylinder
#print axioms measurable_recordPrefix_section
#print axioms measurable_recorderFrontier
#print axioms measurable_recorderFrontier_section
#print axioms recorder_mark_cylinder

end
end WongAdaptiveSelection
