"""Independent exhaustive check of the adjacent-copy plane-tree screen.

No import of all_level_screen.py and no dynamic programming on quartet sets.
Trees are generated by inserting the new rightmost leaf along the right spine.
Quartets are read from graph distances using the four-point criterion.  Each
quartet's copy choices extend to global choices; additionally, one representative
of every discovered quartet system is checked by explicit global copy choices.
"""
from fractions import Fraction
from hashlib import sha256
from itertools import combinations, product
import json
from pathlib import Path
import platform
import sys
import time


def rightmost_insertions(tree, leaf):
    """Every legal insertion of a new final leaf, with no duplicates."""
    yield (tree, leaf)
    if isinstance(tree, tuple):
        for subtree in rightmost_insertions(tree[1], leaf):
            yield (tree[0], subtree)


def tree_families(max_tips):
    # Position 0 is attached above the root.  The remaining positions are the
    # ordered leaves of an ordinary rooted full binary tree.
    families = {2: (1,)}
    for tips in range(3, max_tips + 1):
        families[tips] = tuple(
            new_tree
            for old_tree in families[tips - 1]
            for new_tree in rightmost_insertions(old_tree, tips - 1)
        )
        assert len(set(families[tips])) == len(families[tips])
    return families


def leaf_distances(tree, tips):
    adjacency = [[] for _ in range(tips)]

    def build(node):
        if isinstance(node, int):
            return node
        vertex = len(adjacency)
        adjacency.append([])
        for child in node:
            child_vertex = build(child)
            adjacency[vertex].append(child_vertex)
            adjacency[child_vertex].append(vertex)
        return vertex

    root = build(tree)
    adjacency[0].append(root)
    adjacency[root].append(0)
    assert len(adjacency) == 2 * tips - 2
    assert sum(map(len, adjacency)) == 2 * (len(adjacency) - 1)
    assert all(len(adjacency[i]) == 1 for i in range(tips))
    assert all(len(adjacency[i]) == 3 for i in range(tips, len(adjacency)))
    matrix = []
    for start in range(tips):
        distance = [-1] * len(adjacency)
        distance[start] = 0
        queue = [start]
        for vertex in queue:
            for neighbor in adjacency[vertex]:
                if distance[neighbor] == -1:
                    distance[neighbor] = distance[vertex] + 1
                    queue.append(neighbor)
        assert min(distance) == 0
        matrix.append(distance[:tips])
    return matrix


def quartet_bit(distance, positions):
    a, b, c, d = positions
    sums = (
        distance[a][b] + distance[c][d],
        distance[a][c] + distance[b][d],
        distance[a][d] + distance[b][c],
    )
    smallest = min(sums)
    index = sums.index(smallest)
    other = [value for i, value in enumerate(sums) if i != index]
    assert other[0] == other[1] and smallest < other[0], (positions, sums)
    return 1 << index


def quartet_system(distance, locations, quartets):
    codes = []
    evaluations = 0
    for quartet in quartets:
        displayed = set()
        for chosen in product(*(locations[label] for label in quartet)):
            displayed.add(quartet_bit(distance, chosen))
            evaluations += 1
        codes.append(sum(displayed))
    return tuple(codes), evaluations


def global_choice_system(distance, locations, quartets):
    displayed = [set() for _ in quartets]
    choices = 0
    for chosen in product(*locations):
        choices += 1
        for index, quartet in enumerate(quartets):
            positions = tuple(chosen[label] for label in quartet)
            displayed[index].add(quartet_bit(distance, positions))
    return tuple(sum(bits) for bits in displayed), choices


def coefficients(n, quartets, system, singleton_cherry_entry=Fraction(0), require_nonnegative=True):
    data = dict(zip(quartets, system))
    stats = {"count": 0, "minimum": None, "maximum": None,
             "quotients_checked": 0, "two_topology_quotients": 0,
             "nonintegral_quotients": 0, "singleton_cherry_entries": 0,
             "first_negative": None}
    for p, q in combinations(range(n), 2):
        values = {}
        for x, y in combinations(range(n), 2):
            if {x, y} == {p, q}:
                value = Fraction(0)
            elif {x, y}.intersection((p, q)):
                value = Fraction(1)
            else:
                quartet = tuple(sorted((x, y, p, q)))
                a, b, c, d = quartet
                sides = ((a, b), (a, c), (a, d))
                code = data[quartet]
                present = [sides[index] for index in range(3) if code & (1 << index)]
                separated = sum((x in side) != (y in side) for side in present)
                value = Fraction(2 * separated, len(present))
                if len(present) == 1 and separated == 0:
                    stats["singleton_cherry_entries"] += 1
                    value = Fraction(singleton_cherry_entry)
                stats["quotients_checked"] += 1
                stats["two_topology_quotients"] += len(present) == 2
                stats["nonintegral_quotients"] += value.denominator != 1
            values[x, y] = values[y, x] = value
        for x in range(n):
            values[x, x] = Fraction(0)
        for i, j in combinations(range(n), 2):
            a, b, c, d = i, (i + 1) % n, j, (j + 1) % n
            alpha = values[a, c] + values[b, d] - values[a, d] - values[b, c]
            stats["count"] += 1
            stats["minimum"] = alpha if stats["minimum"] is None else min(stats["minimum"], alpha)
            stats["maximum"] = alpha if stats["maximum"] is None else max(stats["maximum"], alpha)
            if alpha < 0 and stats["first_negative"] is None:
                stats["first_negative"] = {"anchors": [p, q], "boundary_indices": [i, j],
                                           "system": list(system), "alpha": str(alpha)}
            if require_nonnegative:
                assert alpha >= 0, (n, p, q, i, j, system, str(alpha))
    stats["minimum"] = str(stats["minimum"])
    stats["maximum"] = str(stats["maximum"])
    assert stats["nonintegral_quotients"] == 0
    return stats


def file_hash(path):
    return sha256(path.read_bytes()).hexdigest()


def add_modified_check(report):
    started = time.monotonic()
    result = {
        "status": "PASS_MODIFIED_NANUQ_ENDPOINT_ON_SAVED_SYSTEMS",
        "scores": {"cherry": "1/2", "separated": "1", "adjacent": "1/2", "opposite": "1"},
        "entry_change": "Only a disjoint queried pair forming a cherry in a singleton displayed quartet changes from 0 to 1.",
        "method": "Exact rational coefficient evaluation on the stored quartet-system tuples; no tree generation.",
        "verifier_sha256": file_hash(Path(__file__).resolve()),
        "rows": [],
        "failure": None,
    }
    for saved in report["rows"]:
        n = saved["taxa"]
        quartets = tuple(combinations(range(n), 4))
        row = {"taxa": n, "systems": len(saved["quartet_systems"]),
               "anchor_coefficients": 0, "changed_queried_entries": 0,
               "minimum_alpha": None, "maximum_alpha": None}
        for system in saved["quartet_systems"]:
            stats = coefficients(n, quartets, system, singleton_cherry_entry=Fraction(1), require_nonnegative=False)
            row["anchor_coefficients"] += stats["count"]
            row["changed_queried_entries"] += stats["singleton_cherry_entries"]
            lo, hi = Fraction(stats["minimum"]), Fraction(stats["maximum"])
            row["minimum_alpha"] = lo if row["minimum_alpha"] is None else min(row["minimum_alpha"], lo)
            row["maximum_alpha"] = hi if row["maximum_alpha"] is None else max(row["maximum_alpha"], hi)
            if stats["first_negative"] and result["failure"] is None:
                result["failure"] = {"taxa": n, **stats["first_negative"]}
        row["minimum_alpha"] = str(row["minimum_alpha"])
        row["maximum_alpha"] = str(row["maximum_alpha"])
        assert row["anchor_coefficients"] == saved["anchor_coefficients"]
        result["rows"].append(row)
    if result["failure"]:
        result["status"] = "FAIL_MODIFIED_NANUQ_ENDPOINT_ON_SAVED_SYSTEMS"
    result["total_anchor_coefficients"] = sum(row["anchor_coefficients"] for row in result["rows"])
    result["total_changed_queried_entries"] = sum(row["changed_queried_entries"] for row in result["rows"])
    result["elapsed_seconds"] = round(time.monotonic() - started, 3)
    report["modified_nanuq"] = result


def modified_only():
    folder = Path(__file__).resolve().parent
    receipt = folder / "independent-all-level-check.json"
    receipt_bytes = receipt.read_bytes()
    report = json.loads(receipt_bytes.decode("utf-8"))
    assert report["status"] == "PASS_EXHAUSTIVE_FINITE_REPRESENTATION_CHECK"
    current_input_hashes = {name: file_hash(folder / name) for name in report["input_sha256"]}
    add_modified_check(report)
    report["modified_nanuq"]["reused_receipt_sha256"] = sha256(receipt_bytes).hexdigest()
    report["modified_nanuq"]["current_input_sha256"] = current_input_hashes
    report["modified_nanuq"]["inputs_unchanged_since_enumeration"] = current_input_hashes == report["input_sha256"]
    report["modified_nanuq"]["input_scope"] = "The endpoint check uses the systems in the saved exhaustive receipt. It does not revalidate subsequently edited source inputs."
    reference = json.loads((folder / "all-level-screen.json").read_text(encoding="utf-8"))
    report["modified_nanuq"]["matches_current_reference_counts"] = all(
        row["anchor_coefficients"] == next(item for item in reference["rows"] if item["taxa"] == row["taxa"])["modified_anchor_coefficients"]
        for row in report["modified_nanuq"]["rows"]
    )
    receipt.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps(report["modified_nanuq"], indent=2), flush=True)


def run():
    started = time.monotonic()
    folder = Path(__file__).resolve().parent
    expected = json.loads((folder / "all-level-screen.json").read_text(encoding="utf-8"))
    assert expected["failure"] is None
    families = tree_families(12)
    report = {
        "status": "PASS_EXHAUSTIVE_FINITE_REPRESENTATION_CHECK",
        "scope": "All fixed-order unrooted binary plane trees with 3..6 labels, each appearing once or twice adjacently; no source-network coverage claim.",
        "method": "Direct rightmost-leaf insertion, explicit graph shortest paths, four-point quartets, rational anchor coefficients; no import or execution of the target screen.",
        "input_sha256": {name: file_hash(folder / name) for name in ("all_level_screen.py", "all-level-screen.json")},
        "verifier_sha256": file_hash(Path(__file__).resolve()),
        "python": platform.python_version(),
        "tree_family_counts_by_expanded_tip_count": {str(k): len(v) for k, v in families.items()},
        "rows": [],
        "limits": [
            "This checks the stated adjacent-copy representation, not representation of every source network or a compression theorem.",
            "A quartet system is the union across displayed trees. It does not assert simultaneous realization of all quartets by a single displayed tree.",
            "No proof assistant or external theorem prover was run.",
        ],
    }
    for n in range(3, 7):
        quartets = tuple(combinations(range(n), 4))
        systems = {}
        row = {"taxa": n, "duplication_masks": 0, "plane_trees_represented": 0,
               "distinct_quartet_systems": 0, "anchor_coefficients": 0,
               "four_point_copy_quartets": 0, "global_choice_representatives": 0,
               "global_copy_choices_checked": 0, "quotients_checked": 0,
               "two_topology_quotients": 0, "nonintegral_quotients": 0,
               "minimum_alpha": None, "maximum_alpha": None, "mask_rows": []}
        for mask in range(1 << n):
            labels = tuple(label for label in range(n) for _ in range(1 + ((mask >> label) & 1)))
            locations = tuple(tuple(i for i, label in enumerate(labels) if label == x) for x in range(n))
            seen_for_mask = set()
            for tree in families[len(labels)]:
                distance = leaf_distances(tree, len(labels))
                system, evaluations = quartet_system(distance, locations, quartets)
                row["plane_trees_represented"] += 1
                row["four_point_copy_quartets"] += evaluations
                assert all(code in (1, 4, 5) for code in system), (n, mask, tree, system)
                seen_for_mask.add(system)
                if system not in systems:
                    global_system, choices = global_choice_system(distance, locations, quartets)
                    assert global_system == system
                    row["global_choice_representatives"] += 1
                    row["global_copy_choices_checked"] += choices
                    stats = coefficients(n, quartets, system)
                    row["anchor_coefficients"] += stats["count"]
                    for key in ("quotients_checked", "two_topology_quotients", "nonintegral_quotients"):
                        row[key] += stats[key]
                    lo, hi = Fraction(stats["minimum"]), Fraction(stats["maximum"])
                    row["minimum_alpha"] = lo if row["minimum_alpha"] is None else min(row["minimum_alpha"], lo)
                    row["maximum_alpha"] = hi if row["maximum_alpha"] is None else max(row["maximum_alpha"], hi)
                    systems[system] = {"duplication_mask": mask, "tree": tree}
            row["duplication_masks"] += 1
            row["mask_rows"].append({"mask": mask, "expanded_tips": len(labels),
                                     "trees": len(families[len(labels)]),
                                     "distinct_quartet_systems": len(seen_for_mask)})
        row["distinct_quartet_systems"] = len(systems)
        row["minimum_alpha"] = str(row["minimum_alpha"])
        row["maximum_alpha"] = str(row["maximum_alpha"])
        row["quartet_systems"] = [list(system) for system in sorted(systems)]
        reference = next(item for item in expected["rows"] if item["taxa"] == n)
        base_keys = ("taxa", "duplication_masks", "plane_trees_represented", "distinct_quartet_systems", "anchor_coefficients")
        row["matches_reference_counts"] = all(row[key] == reference[key] for key in base_keys)
        assert row["matches_reference_counts"], (reference, row)
        report["rows"].append(row)
        print(json.dumps({key: value for key, value in row.items() if key not in ("mask_rows", "quartet_systems")}), flush=True)
    report["elapsed_seconds"] = round(time.monotonic() - started, 3)
    report["total_trees"] = sum(row["plane_trees_represented"] for row in report["rows"])
    report["total_four_point_copy_quartets"] = sum(row["four_point_copy_quartets"] for row in report["rows"])
    report["total_anchor_coefficients"] = sum(row["anchor_coefficients"] for row in report["rows"])
    add_modified_check(report)
    receipt = folder / "independent-all-level-check.json"
    receipt.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({"status": report["status"], "receipt": str(receipt),
                      "total_trees": report["total_trees"], "elapsed_seconds": report["elapsed_seconds"]}), flush=True)


if __name__ == "__main__":
    if sys.argv[1:] == ["--modified-only"]:
        modified_only()
    else:
        assert not sys.argv[1:], "The only optional argument is --modified-only"
        run()
